name: smart_travel_app
)description: Smart Travel Assistant - AI powered crowd-aware travel planner
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Networking
  http: ^1.1.0

  # Google Maps
  google_maps_flutter: ^2.6.0

  # UI icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
